api_version = "2025-04"

[[extensions]]
name = "Volume Discount"
handle = "volume-discount"
type = "function"
uid = "bb2f00de-e779-90e3-7141-d67d5d765661b27f22c4"
description = "Buy 2 get X% off discount"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  enable_create = true